# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed8750df449ee65c175031741b3f88a8e00fbe2c415bf4cc867d665f05ec0a0bfa25ddb94617152fdcf04611ff51176099b361c67101c6fa48ce351b125f47d7

test:
  secret_key_base: 6116dc2bafe2d7371a87da88716904327b62f920b936113a501035d6142eb051317d50f089e660131a2e246cd1604b4317d85580f43123dea86f0ead04b49547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
